libMesh/TIMPI

.travis.yml
src/utilities/include/timpi/timpi_init.h
src/utilities/src/timpi_init.C
test/parallel_sync_unit.C

Swiped wholesale from MetaPhysicL

Added .travis.yml CI tests

---

.travis.yml
configure.ac
test/Makefile.am
test/parallel_sync_unit.C
test/run_unit_tests.sh.in

This PR also disables oversized pull unit tests, because apparently that's never worked perfectly but our test coverage of it has been even worse.

Parallel testing

---

src/parallel/include/timpi/communicator.h
src/parallel/include/timpi/parallel_implementation.h
test/parallel_unit.C

Add map_sum() specialization for non-fixed types

---

.gitmodules

Thanks to @jwpeterson for pointing out the issue in
https://github.com/libMesh/libmesh/pull/2534

Use a relative path for submodules

---

src/algorithms/include/timpi/parallel_sync.h

Use correct send context and rename ReceiveContext

---

src/parallel/include/timpi/status.h

Use defaults in Status

---

src/parallel/include/timpi/status.h

Default constructor and destructor in Status

---

src/algorithms/include/timpi/parallel_sync.h

This fixes a libMesh unit test that was failing for me on some systems
and processor counts.

Oversized pull responses can start above min pid

---

Makefile.am

Refs https://github.com/libMesh/libmesh/issues/2735

Use "-f" when using mv to overwrite our own files

---

src/parallel/include/timpi/communicator.h
src/parallel/include/timpi/parallel_implementation.h
test/parallel_unit.C

@roystgnr probably better to have the conversation here.

Add nonblocking min, max, and sum

---

src/parallel/include/timpi/standard_type.h

Explicitly instantiate DataType superclass for tuple

---

src/parallel/include/timpi/packing.h
test/dispatch_to_packed_unit.C

Also included: fixes for ```Packing<tuple>``` test, and actually running ```Packing<tuple>``` test.

Packing<array> support

---

src/algorithms/include/timpi/parallel_sync.h
test/packed_range_unit.C
test/parallel_sync_unit.C

Generalized push_parallel_[packed_range/vector_data]

---

src/algorithms/include/timpi/parallel_sync.h

Avoid shadowed declarations introduced in #66

---

test/Makefile.am
test/run_unit_tests.sh.in

And see whether our new CIVET recipe works!

Make sure we are testing set with make check

---

src/parallel/include/timpi/packing.h
src/utilities/src/timpi_version.C
test/packed_range_unit.C

Pinging @loganharbour, who managed to trigger the error that this PR fixes for me.  I think I have a decent unit test here, but do you perhaps still got your pre-workaround code handy, so we can try it directly on that too?

Packing size fixes

---

m4/determine_cxx_brand.m4

Requires libMesh/autoconf-submodule#6

Add Intel(R) icc 21 support

---

src/parallel/include/timpi/packing.h

When we communicate variable-size containers of fixed-size classes, this
will require us to be a little strict about those classes' constructors
... but not as impossibly strict as the new gcc warnings would have us
be.
Hopefully this will fix (in combination with some libMesh constructor cleanup)
https://github.com/libMesh/libmesh/issues/3157

Do our own checks before memcpy

---

test/packed_range_unit.C

The "bug" I thought I was chasing turned out to be a red herring, but more test coverage can't hurt.

Add another packed range unit test

---

src/algorithms/include/timpi/parallel_sync.h
src/parallel/include/timpi/standard_type.h
test/dispatch_to_packed_unit.C
test/packed_range_unit.C

I think I want to add some more (testing, at least) to this or a subsequent PR before finishing up TIMPI changes and going downstream, but hopefully this will be the last change Logan needs to stop snarking at me.  "I’ll allow it"...

Auto-dispatch from parallel push to packed_range

---

src/parallel/include/timpi/communicator.h
src/parallel/include/timpi/packing.h
src/parallel/include/timpi/parallel_implementation.h
test/parallel_unit.C
test/set_unit.C

Closes #105 IMHO - @jwpeterson should chime in on that too.
Important bug fix here, too.  If Peter programmer packs a padded pair into packets, how many packets did Peter programmer pack?
I'm just now realizing I haven't yet tested this with --disable-mpi.  Hopefully CI will tell me how bad a mistake that was.

set_union fixes

---

src/parallel/include/timpi/parallel_implementation.h

Not sure why it's only our Mac builds complaining about this.

Fix "template parameter redefines default argument"

---

src/parallel/include/timpi/request.h
src/parallel/src/request.C

Closes #122.
Related Griffin PR : https://github.inl.gov/ncrc/griffin/pull/947

Fix compile error with NVCC and OpenMPI

---

INSTALL
configure.ac

Not sure how I missed this when doing the updates in ACSM and libMesh, but with the ACSM work done there wasn't anything non-trivial left here.

Autotools update

---

src/parallel/include/timpi/communicator.h
src/parallel/include/timpi/parallel_communicator_specializations
src/parallel/include/timpi/parallel_implementation.h
test/set_unit.C

I swear I'd *intended* to write this already, so I was as surprised as the user who needed it to find out it wasn't there.

Multiset (multimap, etc) support in set_union()

---

test/parallel_unit.C

The user report that prompted this turned out to be a red herring, but more test coverage is always better.

AllGather(vector<vector>) in-place test

---

src/parallel/include/timpi/packing.h
src/parallel/include/timpi/packing_decl.h
src/parallel/include/timpi/parallel_implementation.h
src/parallel/include/timpi/serial_implementation.h
test/packed_range_unit.C

This fixes failures for me in John's test in #140

Pass output iterator by reference in unpack_range
