libMesh/TIMPI

src/Makefile.am, src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/packing.h, src/parallel/include/timpi/packing_forward.h, src/parallel/include/timpi/parallel_implementation.h, src/parallel/include/timpi/standard_type.h, test/Makefile.am, test/dispatch_to_packed_unit.C, test/packed_range_unit.C
This works currently by:
- Adding a `is_fixed_type` bool to StandardType classes
- doing SFINAE on Communicator::allgather based on `is_fixed_type`
This also adds default `typename Enable = void` template arguments to
`StandardType` and `Packing`. This is useful for enabling/disabling
specializations based on whether data members are fixed sizes or not.
I'm thinking of an example like `DualNumber<T,D>` where that class
may be fixed-size depending on whether D is fixed-size
=> Dispatch to allgather_packed_range from allgather for dynamic size types

configure.ac, test/Makefile.am, test/parallel_sync_unit.C, test/parallel_unit.C
Damn, this is going to conflict with #5.  I'll fix up after that's merged.
=> Unit test, compilation fixes

Makefile.am, bin/timpi-config.in, configure.ac
This allows querying the necessary TIMPI dependencies when configuring a package that may depend on TIMPI, e.g. MetaPhysicL.
=> Add support for a timpi-config

src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_communicator_specializations, src/parallel/include/timpi/parallel_implementation.h, test/parallel_unit.C
The `map` and `unordered_map` `sum()` implementations are basically identical, so they both simply use the private `Communicator::map_sum()` implementation function.
=> Add Communicator::sum(std::unordered_map)

src/parallel/include/timpi/parallel_implementation.h, test/parallel_unit.C
All other things being equal, it's probably more efficient to broadcast one slightly-larger-than-necessary (due to padding) message than two smaller messages.
Also adds a unit test of Communicator::broadcast(map)
=> Communicator::broadcast(map): Save one communication

src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_implementation.h, test/parallel_unit.C
Use SFINAE based on whether the map types are fixed types in order
to determine whether to call @jwpeterson's single broadcast method
or the old double broadcast method
=> Add back old map broadcast method

test/Makefile.am
Without this PR  a user who has oprof or prof in their `METHODS` variable will get a test failure because the oprof tests won't be built but the `run_unit_tests.sh` script will try to run them.
On a related note, with the addition of `run_unit_tests.sh` (which I'm very appreciate for) I'm guessing there's really no way with autotools to still get the pass/fail for each individual test...it will just be a single pass/fail for the `run_unit_tests.sh` script?
=> Make sure that we can test OPROF and PROF methods

src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_communicator_specializations, src/parallel/include/timpi/parallel_implementation.h
This lets us optimize away a little communication in cases where
containers like set/map/unordered_map can already be sized for their
expected contents, but more importantly it gives us an excuse to *add*
such communication in the broadcast(vector) case, making our default
behavior there more flexible and more consistent with the other
broadcast and other vector APIs.
=> Add identical_sizes argument to broadcast

.travis.yml, src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_communicator_specializations, src/parallel/include/timpi/parallel_implementation.h
Hopefully this way it'll get passed down to our run_unit_tests.sh and
we'll *actually* be running them in parallel.
Simply setting the variable without exporting it in #12 didn't work.
With luck we'll now see the tests fail, as there's an overzealous unit test (or IMHO an insufficiently flexible API) among the ones @jwpeterson introduced in #10.  I'll commit a fix for the API in a separate PR.
=> export TIMPI_RUN in Travis MATRIX_EVAL

src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_communicator_specializations, src/parallel/include/timpi/parallel_implementation.h, test/parallel_unit.C
Similar to broadcast(map) and sum(map), this is based on a shared private Communicator::map_max() implementation so that it works for both std::map and std::unordered_map.
There are two versions of Communicator::map_max(), one for fixed types and one for non-fixed types. The SFINAE principal is used to control which version gets called.
=> Add Communicator::max(map)

src/Makefile.am, src/algorithms/include/timpi/parallel_sync.h, src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_communicator_specializations, src/parallel/include/timpi/parallel_implementation.h, src/parallel/include/timpi/post_wait_unpack_nested_buffer.h
This lets us get rid of the parallel_sync.h overloads with the alltoall step, so now every single sync function there uses the NBX algorithm as adapted by @friedmud.  Fixes #18.
=> Nonblocking vec<vec> receives + syncs

Makefile.am, src/Makefile.am, test/Makefile.am
- Add */timpi_config.h to DISTCLEAN. I believe this actually caused
me a nasty "bug" at one point where I was compiling TIMPI with
a different config than what I was compiling a downstream app.
Moreover, this meets the definition of a configure-generated file
and hence should be included in `make distclean`. This is
not currently caught by the default `make distclean` target
- Remove the MAINTAINERCLEANFILES targets. According to the automake
manual: "maintainer-clean should not delete anything that needs to
exist in order to run configure and make"
- Add prof and oprof targets for `timpi_version`
=> automake fixups

src/parallel/include/timpi/parallel_communicator_specializations, src/parallel/include/timpi/parallel_implementation.h, test/dispatch_to_packed_unit.C
=> Add dispatch to packed range broadcast

src/parallel/include/timpi/packing.h, src/parallel/include/timpi/standard_type.h, test/dispatch_to_packed_unit.C
This specialization is enabled when the std::pair is not of fixed
size, e.g. when either first or second is not of fixed size.
Size of first and second are computed using sizeof when
one is of fixed size, and using Packing::*size when not of fixed
size. I also introduce a couple of helper structs in order to
"automatically" determine the buffer_type for the Packing<pair>
specialization
=> Create a Packing specialization for std::pair

m4/mpi.m4
This may be at the root of how a bad CPPFLAGS setting was getting
incorporated into libMesh builds using Conda
=> Don't swap LIBS and CPPFLAGS

src/algorithms/include/timpi/parallel_sync.h, src/parallel/include/timpi/packing.h, src/parallel/include/timpi/parallel_implementation.h, test/packed_range_unit.C
This fixes the possibly-unused-variable warning that had my --enable-werror libMesh build screaming at me, along with some other fixes I saw along the way, a big expansion of compatibility with more container types, and a couple unit tests.
Haven't tested this with the fixed libMesh node constraints code yet, but I'll do that before I hit merge.
=> push_parallel_packed_range fixes and improvements

src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_implementation.h, src/parallel/include/timpi/serial_implementation.h
This adds optional approx_buffer_size arguments to as many more packed_range functions as possible, and in the case where it's impossible (allgather dispatch as in #5) tries to choose a buffer size that won't overflow regardless of problem size.
Thanks to @fdkong for tracking this down.  This is the first step of the fix, but we're going to actually have to *use* the new parameter in one or two places in libMesh before his runs will be safe.
=> Better packed_range buffer size control

bootstrap
If we bootstrap without it then we get confusing error messages at configure time from the unresolved m4 macros.
=> Have bootstrap check for autoconf submodule initialization

src/algorithms/include/timpi/parallel_sync.h, src/parallel/include/timpi/standard_type.h
This avoids destroying and reallocating a StandardType on each NBX loop, which was taking up a ton of time in some of our profiling.  Fingers crossed, this might fix a recent performance regression *and* further improve a recent performance optimization.
On the other hand, with this change we may just end up busy looping more often, rather than actually finishing communications faster.
@fdkong, could you try this out on the same problem you've been profiling for me?  I'd love to see how the gperftools output changes.
=> Cache StandardType in push_parallel_vector_data

src/algorithms/include/timpi/parallel_sync.h
@jwpeterson pointed out to me that we're relying heavily here on a lot
of indirect inclusions via parallel_implementation.h
=> Directly include header files in parallel_sync.h

src/parallel/include/timpi/data_type.h
As long as we're at it, couldn't hurt to have move arguments supported
here.
I skimmed through the rest of TIMPI; other than Status this was the only obvious candidate for default functions.
Pinging @jwpeterson and @loganharbour
=> Default DataType constructor/destructor/assignment

configure.ac, src/algorithms/include/timpi/parallel_sync.h, src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/data_type.h, src/parallel/include/timpi/packing.h, src/parallel/include/timpi/parallel_communicator_specializations, src/parallel/include/timpi/parallel_implementation.h, src/parallel/include/timpi/serial_implementation.h, src/parallel/include/timpi/standard_type.h, test/dispatch_to_packed_unit.C
@roystgnr has expressed his dislike of the `is_fixed_type` idiom, and I
never loved it either. So let's use the member detector idioms
that are already well known in C++. Something should be sendable
using MPI_Datatype if the `StandardType<T>` specialization inherits
from `Datatype` which has the `_datatype` member indicating an
MPI_Datatype. This kind of thinking requires that `StandardType`
specializations which are not sendable via `MPI_Datatype` **do not**
inherit from `Datatype`. Removing that inheritance also makes it impossible
to call a `Communicator` API that takes a `TIMPI::Datatype` with an object that actually doesn't
support sending via `MPI_Datatype`.
Moreover, I don't think we should enable templates just because something
**is not** true. We should only emplate templates …
=> More dispatches to packed range; displace is_fixed_type idiom

src/utilities/include/timpi/ignore_warnings.h
Not sure this is the safest warning to ignore, but it's triggering on
Ubuntu OpenMPI's mpi.h for me.
=> Add -Wcast-align to clang ignore_warnings.h

configure.ac, src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_implementation.h, src/parallel/include/timpi/serial_implementation.h, test/parallel_unit.C
The use of `#ifdef TIMPI_HAVE_MPI` in `communicator.h` goes against the current design, but it's certainly the fewest lines of code to fix #55 I think. If there's a cleaner solution, then I'll change things here. The `allgather` implementation in `serial_implementation` is necessary otherwise we'll get undefined references when trying to link the unit tests (with the new `testAllGatherString` test)
Also refs libmesh/libmesh#2791
=> Ensure methods with SFINAE abling can be used in serial

src/parallel/include/timpi/standard_type.h
This is needed for compatibility with libMesh::SparsityPattern::Row,
which uses a scalable_allocator in threaded configurations.
=> Support build_standard_type w/ user allocators

src/parallel/include/timpi/packing.h, src/parallel/include/timpi/standard_type.h, test/dispatch_to_packed_unit.C
This gives us a Packing specialization for any tuple that's not completely composed of fixed types, and removes those cases from the previous StandardType specialization, so variable-size data structures with tuples in them can now participate in automatic packing dispatch.
Hoping @lindsayad can look this over too; he did much of the hard work this is based on.
And, if it's not too late, @loganharbour might want to try this out, since he was the first one to try to communicate a vector of tuples with strings in them under the naive theory that just because we supported vectors and tuples and strings that would mean we must support vectors of tuples of strings too.
=> Packing<tuple> specialization

src/parallel/include/timpi/standard_type.h, test/parallel_unit.C
This lets us use ```std::array<T,N>``` for fixed-size datatype communications, with any T for which ```StandardType<T>``` exists.
=> StandardType<std::array> support

src/parallel/include/timpi/post_wait_dereference_tag.h
This silences a warning I was getting from GCC's -Wsuggest-override.
=> Add override keyword

src/parallel/include/timpi/packing.h, src/parallel/include/timpi/parallel_communicator_specializations, src/parallel/include/timpi/parallel_implementation.h, test/Makefile.am, test/set_unit.C
This is hopefully sufficient to solve the issue in #69, and hopefully won't break (or pessimize, if our custom vector<vector> overloads were to suddenly stop getting preferred to packed_range dispatch) any other code paths, but I'm not 100% certain of any of that.
=> Packing<vector> support, set_union unit tests

.gitignore, src/Makefile.am, src/parallel/include/timpi/standard_type.h, src/parallel/include/timpi/standard_type_forward.h
Because the StandardType template takes a defaulted argument, it's
important to ensure that any declarations ahead of the class definition
illustrate that (otherwise the compiler wil error)
=> Add StandardType forward declaration header

src/parallel/include/timpi/data_type.h
As evidenced by the number of errors I get if I make this destructor
protected, we delete from `DataType` quite a bit. Consequently we have
to make sure that the `StandardType` destructor gets called because that
is generally what calls `free()`. This is ultimately what slew
idaholab/moose#19246, causing valgrind errors in
https://civet.inl.gov/job/880361/, and leading to reversion in
idaholab/moose#19331
=> Make DataType destructor virtual

src/parallel/include/timpi/standard_type.h, test/parallel_unit.C
Maybe I can drum up a test that would not have been valgrind clean before this change. Shouldn't be very hard
=> Implement copy assignment operators for StandardType

src/Makefile.am, src/parallel/include/timpi/op_function.h, src/utilities/include/timpi/semipermanent.h, src/utilities/include/timpi/timpi_init.h, src/utilities/src/semipermanent.C, src/utilities/src/timpi_init.C, test/parallel_unit.C
This solves the tiny leak in our quad-precision on-the-the-fly-`MPI_Op` support, and more importantly it extends that support to std::pair and adds a unit test for it.  There's still a ton of work to be done here (and in MetaPhysicL), but I'm throwing this up now that it's passing tests, to see if anyone (or any CI tests) has criticisms.
This is our first-ever "do not merge"-labeled TIMPI PR because I'm still not 100% sure of the API myself.  I think I may move the new static members and APIs from `TIMPIInit` to `SemiPermanent` (even though the `TIMPIInit` destructor will still have to access them, we can make it a friend class), and I should probably replace `FreeOp` with something that does both halves of the create+free, to make that be a proper RAII class.
=> Expanded OpFunction capabilities

src/parallel/include/timpi/standard_type.h, src/utilities/src/timpi_init.C
In #38 we got a few percent speedup by pulling a `MPI_Type_commit/MPI_Type_free` pair out of one inner loop, but by using the SemiPermanent capability from #80 we can avoid redundant derived type creations and deletions entirely.
This still makes valgrind happy for me, but on my system it took extra valgrind options to reliably sense any bugs, so I'll wait to merge until after our CI recipes have been updated to add the extra options and I kick the branch to use the updated recipes.
=> Use SemiPermanent for derived StandardType classes

configure.ac, m4/acsm_cxx_tests.m4
This should keep us working with older compilers (once that support
C++14 but don't default to it) for a little longer, until we're ready for C++17.
=> Update compiler requirements from C++11 to C++14

src/algorithms/include/timpi/parallel_sync.h, test/parallel_sync_unit.C
Random improvements while I'm digging through this.
Will probably need `timpi_make_unique` for c++ 11
=> Simplify logic in parallel sync nbx helper

test/parallel_unit.C
After updating my compiler and libMesh-library, I got fetched by [gcc's spurious warning](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100366) which was resolved in the analogous [libmesh-test](https://github.com/libMesh/libmesh/pull/3097#discussion_r764063418).
For some reason, you seemingly never ran into this?
(my gcc-version is 11.2.0).
Best regards
=> prevent gcc spurious warnings

src/parallel/include/timpi/packing.h
This was enough for our own classes, but it still gives false positives
for C++ standard classes.  Testing for a StandardType should have been
enough here.
Refs #90
=> Remove static_assert(is_trivially_copyable)

src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_implementation.h, test/dispatch_to_packed_unit.C
This also lets us do set_union on sets or maps whose data types aren't
fixed-size.
=> Let gather auto-dispatch to gather_packed_range

src/Makefile.am
This lets us do things like using linker flags instead of wrapper
scripts to get MPI support, which I need to test with my system's
clang++ 13 without rolling my own MPI on top of it.
=> Append to $LIBS, don't override $LIBS

src/parallel/include/timpi/packing.h
We define these functions for particular specializations, but in each
case we have headers declaring those specializations and we don't need
the general declaration here.  Leaving the general declaration here just
makes it more confusing to debug when someone has the general header
included but not the particular specialized header(s) they need.
=> Don't declare functions we can't define

test/parallel_unit.C
I was getting false errors from semiverify() tests in an application
code path; the result appears to be a regression in OpenMPI 4.1.2, but
the extra tests I added while determining that might as well go into the
library proper.
=> More parallel unit testing

src/parallel/include/timpi/packing.h
Maybe we'll find a better workaround here for the future, but for now
this fixes `--enable-paranoid-warnings --enable-werror` builds on gcc
11.2.0 for me.
=> Ignore stack-protector warnings around our memcpys

src/parallel/include/timpi/packing.h, test/packed_range_unit.C
Somehow the old code here still compiled *if* the tuple contents weren't mixes of packed and fixed-size types *or if* the tuple contents were in the "right" (non-broken) order.
=> Bugfix for Packing<tuple>

src/Makefile.am, src/parallel/include/timpi/packing.h, src/parallel/include/timpi/packing_decl.h
Not sure if this was necessary to fix the bug I just fixed, but it's at least sufficient, and it may end up being necessary for future cases of `Packing` with trickily-nested types.
=> Break out Packing declarations in their own header

src/utilities/include/timpi/timpi_assert.h
This category of warnings is in recent years being hit by a large
collection of programmers who are writing distributed-parallel codes for
the first time and could benefit from clearer messages when they get out
of sync, as opposed to the original collection of programmers who the
category was designed for, {me}.
=> Better messages when timpi_parallel_only() fails

src/algorithms/include/timpi/parallel_sync.h, test/packed_range_unit.C, test/parallel_sync_unit.C
We do so with the public APIs so let's do it with the helper too
=> Carry rvalue references through the nbx helper

src/parallel/include/timpi/packing.h, src/parallel/include/timpi/packing_decl.h, src/parallel/include/timpi/standard_type.h, test/packed_range_unit.C
A `container<SomethingUnpackable>` should itself be recognized as unpackable, even if other `container<T>` can be handled.
This should let user code test `Has_buffer_type<Packing<T>>::value` and see false for types we can't pack.
I ought to throw some `static_assert(!Has_buffer_type<Packing<Foo>>::value)` for a bunch of unpackable foo into the test suite before we merge this, but the headers should be in shape for Logan to play with.
=> Don't define `Packing` specializations we can't pack

src/algorithms/include/timpi/parallel_sync.h, src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_communicator_specializations, src/parallel/include/timpi/parallel_implementation.h, src/parallel/include/timpi/serial_implementation.h, src/parallel/src/communicator.C, test/dispatch_to_packed_unit.C, test/packed_range_unit.C, test/parallel_sync_unit.C
This might be interesting when benchmarking the new algorithms, and it might be useful when debugging weird parallel failures or MPI stacks, or it might only be useful because it adds test coverage for a bunch of previously uncovered overloads.
=> Options to use older sync algorithms

src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_implementation.h
Newer compilers don't seem to complain about function parameters shadowing other function names, but gcc 7.5 doesn't like seeing "send" in one of our new overload implementations.  Let's just rename it everywhere.
=> Avoid shadowing send()

src/algorithms/include/timpi/parallel_sync.h
Logan got bit by this in the ray tracing code.
In a sense this is making the sync code less useful, because someone could be legitimately sending a message with an empty container (just as we tend to attach special meaning to a nullptr) ... but more likely an empty container is a performance bug; he says it was in his cases.
Also, we *can't* support sending empty containers as messages in the round-robin backend, so if we want to be able to swap that in we need the same restrictions elsewhere.
We do fear that some code will only generate empty sends at high processor counts, making assertion failures here tricky to debug, but since an assertion will never bring down an opt-mode simulation, that should be reasonable enough.
=> Assert !sending empty vectors even with NBX

src/parallel/include/timpi/communicator.h, src/parallel/src/communicator.C, test/parallel_sync_unit.C
This better enables setting this sync type via parameters or cli args.
=> Add Communicator::sync_type setter via a string

src/algorithms/include/timpi/parallel_sync.h
This wasn't a problem when the function was only getting invoked via one object file's main(), but "duplicate symbol" becomes a problem when it's getting invoked via a dozen different compliation units in the same library downstream.
=> Add missing inline keyword

src/parallel/include/timpi/parallel_implementation.h, src/parallel/src/communicator.C, test/parallel_unit.C
@NamjaeChoi - can you see if this still gives you `-fsanitize=integer` complaints?  I'll need to do a little futzing to get a clang+MPI build working myself.
=> Sanitize and test vector<bool> specializations

test/packed_range_unit.C
=> Get rid of deprecated std::iterator

src/utilities/include/timpi/timpi_call_mpi.h, src/utilities/src/timpi_init.C
For some reason this *doesn't* seem to bother clang's
`fsanitize=integer`, and any negative error codes ought to survive the
round-trip conversion, but let's conform better anyway.
=> MPI_* return int, not unsigned int 

configure.ac, src/parallel/include/timpi/packing.h
This silences a warning from nvc++, and maybe it helps easily-confused compilers optimize better too.
=> Use "if constexpr" if we can

m4/timpi_set_cxx_flags.m4
I don't think this is likely to ever be important, since we don't enable FPE in our test suite and we're surely never going to be doing vectorizable operations in the tiny parts of the TIMPI library that aren't header-only ... but I do want to keep ACSM in sync, and if FPE safety in TIMPI *is* ever important I'd rather we be too safe than not-safe-enough.
=> Use FPE-safety flags when compiling TIMPI

src/parallel/src/request.C
Only one new compiler warning this time.
=> Get a clean `make check` from NVidia HPC SDK 24.7

src/parallel/include/timpi/packing.h
In the branch where we enter this if block, we're not doing an excessive shift, but nvc++ warns about it anyway, presumably compiling the block before realizing it can be optimized away.
=> Workaround for compiler warning in unused code

src/utilities/include/timpi/timpi_init.h, src/utilities/src/timpi_init.C
The direct solver package strumpack leverages the package slate which requires `MPI_THREAD_MULTIPLE`. E.g. without the ability to require higher levels of mpi thread support, we get errors like this
```
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: No support for this operation on this system
[0]PETSC ERROR: SLATE requires MPI_THREAD_MULTIPLE
```
=> Enable `MPI_THREAD_SERIALIZED` and `MPI_THREAD_MULTIPLE`

src/parallel/src/communicator.C
This made me doubt for a second about libMesh/libmesh#4041 but I'm pretty sure the communicator must include at least the querying process, as we shielded with `_communicator != MPI_COMM_NULL`.
=> Assert comm size is strictly greater than 0

src/parallel/include/timpi/parallel_implementation.h, src/parallel/include/timpi/serial_implementation.h
We have users with non-assignable output iterator types; this fixes backwards compatibility for them.  I don't like doing heap allocation on a tiny little iterator here, but we only do it once for every time we allocate up to 4MB of buffers on the heap so I'm sure it won't show up in profiling.
=> Use copy construction on out_iter, not assignment

src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_implementation.h
Otherwise, the compiler (at least gcc 13.3) can't prove we're not in the parallel branch, and it notices that the parallel branch doesn't touch its output, and it emits a maybe-uninitialized warning in a unit tests where we didn't initialize the output variable ourselves.
I considered adding ifdef blocks to a zillion other cases here as well, since "the compiler can't prove we're not in the parallel branch" has optimization implications as well, but it turns out that a better solution is "help the compiler prove we're in the parallel branch", so I added that instead, and verified that (at least with gcc 13.3) it also is sufficient to fix the maybe-uninitialized warning, which at least implies that *part* of the compiler code can elide an `if (1 > 1)` block.  I'll leave the first commit in …
=> Fix uninitialized warning

src/parallel/include/timpi/communicator.h, src/parallel/include/timpi/parallel_implementation.h, src/parallel/include/timpi/post_wait_unpack_nested_buffer.h, src/parallel/include/timpi/status.h
I just saw a user get hit by a 2B size limit in their PETSc build, and once they get their PETSc support squared away I'm worried that they'll hit the same limit from us unless we fix it preemptively.
This is passing our existing unit tests with no regression, but at some point I'm going to need to add a unit test option to send around gigabytes of data and make sure we actually see progress too...
=> Use MPI-4 APIs for MPI_Count (i.e. 64-bit) size support, when available

src/parallel/include/timpi/parallel_implementation.h, src/parallel/include/timpi/post_wait_unpack_nested_buffer.h
Making COUNT_TYPE a variable was giving us linking failures from multiple definitions, and isn't really necessary.  Using CountType in places where we needed DispType was giving us compilation errors for some methods that clearly need more internal test coverage rather than just indirect MOOSE/libMesh coverage.
=> MPI-4 support fixes

Makefile.am, src/utilities/include/timpi/timpi_version.h.in, src/utilities/src/timpi_version.C, test/Makefile.am, test/message_tag_unit.C, test/utility_unit.C
After seeing one of those MPI-4-interface bugs make it past our CI before getting tripped in libMesh testing, I decided to try increasing our coverage.
This seems like a losing battle with old-but-misbehaving lcov on our CI boxes and new-but-misbehaving-differently lcov on my workstation, but we should merge what progress I've made.
=> Raise coverage

test/packed_range_unit.C, test/set_unit.C
I was about to use a C++17-only feature on purpose, then wondered how many we've been starting to use by accident...
=> Fix unit tests with C++14 compilers

src/parallel/include/timpi/attributes.h
We had a bool for code to test before trying to use these, but it's better to just not even *allow* code to try to use these; it's invariably going to be a bug, like the one we just fixed in libMesh.
=> Don't provide default Attributes<T>::set_*

src/parallel/include/timpi/communicator.h
This fixes a compile error I get.
`uint*_t` are used a few lines down for `processor_id_type` typedef.
=> Include cstdint in communicator.h
